### ISSUE TITLE
How sensible is paco from pypaco to the selection of the seed?

### ISSUE THREAD

**Issue by sauveregarder** [CarloNicolini/paco#8]
I'm using the function paco from pypaco and am getting widely different results depending on which seed I give.

**Comment by CarloNicolini** [comment]
It is normal behavior.
For this reason you can either choose to run Paco a large number of times
with different seee and get the solution with the highest surprise or
otherwise to create a consensus partition that behaves like a 'median'
partition.


Il ven 8 giu 2018, 05:34 Filipe Albuquerque Russo <notifications@github.com>
ha scritto:
